name: Kerdy Android CI

on:
  push:
    branches: [ "android-main" ]
  pull_request:
    branches: [ "android-main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Change wrapper permissions
      run: chmod +x ./android/2023-emmsale/gradlew
      
    - name: gradlew 초기화
      run: ./android/2023-emmsale/gradlew init
      
    - name: Run ktlint
      run: ./android/2023-emmsale/gradlew ktlintCheck

    - name: Run detekt
      run: ./android/2023-emmsale/gradlew detekt

    - name: Run unit tests
      run: ./android/2023-emmsale/gradlew testDebugUnitTest

    - name: Build assemble release apk
      run: ./android/2023-emmsale/gradlew assembleRelease

    - name: Create android test report
      uses: asadmansr/android-test-report-action@v1.2.0
      if: ${{ always() }}

    - name: Build assemble release apk
      run: ./android/2023-emmsale/gradlew assembleRelease
