name: Kerdy Backend Dev Server CI/CD

on:
  push:
    branches: ["main", "backend-main", "Feature/#37-자동배포_구현"]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: deploy
      run: ~/deploy.sh